from supabase import create_client, Client
import json

with open("settings.json", "r", encoding="utf-8") as f:
    config = json.load(f)

url = config.get("supabase_url")
key = config.get("supabase_secret_key")

supabase: Client = create_client(url, key)

sql_commands = [
    """
    CREATE TABLE IF NOT EXISTS customers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tarih TEXT, ad_soyad TEXT, telefon TEXT, e_posta TEXT, talep_türü TEXT,
        bütçe TEXT, bölge_1 TEXT, bölge_2 TEXT, bölge_3 TEXT, aciliyet TEXT, notlar TEXT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS satilik_konut (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tarih TEXT, ilan_no TEXT, konut_tipi TEXT, fiyat TEXT, bölge_mahalle TEXT,
        oda_sayısı TEXT, kat TEXT, sahibi TEXT, sahibi_tel TEXT, notlar TEXT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS kiralik_konut (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tarih TEXT, ilan_no TEXT, konut_tipi TEXT, fiyat TEXT, bölge_mahalle TEXT,
        oda_sayısı TEXT, kat TEXT, sahibi TEXT, sahibi_tel TEXT, notlar TEXT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS satilik_arsa (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tarih TEXT, ilan_no TEXT, arsa_tipi TEXT, ada TEXT, parsel TEXT,
        fiyat TEXT, bölge_mahalle TEXT, sahibi TEXT, sahibi_tel TEXT, notlar TEXT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS reminders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tarih TEXT, müşteri_adı TEXT, telefon TEXT, hatırlatma_tarihi TEXT, not TEXT
    );
    """
]

print("Tablolar oluşturuluyor...")
for sql in sql_commands:
    try:
        # Supabase Python client doesn't have a direct 'query' or 'sql' method for raw SQL
        # Raw SQL execution is usually done via RPC or not supported directly for security.
        # However, let's try if there's any undocumented way or if we can use Postgrest
        # Since we can't run raw SQL easily via client, we'll inform the user.
        print("Uyarı: Python SDK üzerinden doğrudan tablo oluşturma yetkisi kısıtlı olabilir.")
        break
    except Exception as e:
        print(f"Hata: {e}")

print("\nLütfen Supabase Panel -> SQL Editor kısmından tabloları oluşturun.")
